package com.latewind.domain;
// Generated 2016-5-5 21:53:57 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer departmentId;
	private Position leader;
	private String name;
	private String tel;
	private String func;
	private Set<Position> positions = new HashSet<Position>(0);

	public Department() {
	}

	public Department(Position position, String name, String tel, String func, Set<Position> positions) {
		this.setLeader(position);
		this.name = name;
		this.tel = tel;
		this.func = func;
		this.positions = positions;
	}

	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}



	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getFunc() {
		return this.func;
	}

	public void setFunc(String func) {
		this.func = func;
	}

	public Set<Position> getPositions() {
		return this.positions;
	}

	public void setPositions(Set<Position> positions) {
		this.positions = positions;
	}

	/**
	 * @return the leader
	 */
	public Position getLeader() {
		return leader;
	}

	/**
	 * @param leader the leader to set
	 */
	public void setLeader(Position leader) {
		this.leader = leader;
	}

}
