package com.latewind.domain;
// Generated 2016-5-30 19:15:41 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.latewind.bean.UserInfo;

/**
 * Msg generated by hbm2java
 */
public class Msg implements java.io.Serializable {

	private int id;
	private UserInfo sender;
	private String title;
	private String content;
	private Date sendtime;
	private Set<UserInfo> receivers = new HashSet<UserInfo>(0);

	public Msg() {
	}

	public Msg(int id) {
		this.id = id;
	}

	public Msg(int id, UserInfo sender, String title, String content, Date sendtime, Set<UserInfo> userInfos) {
		this.id = id;
		this.sender = sender;
		this.title = title;
		this.content = content;
		this.sendtime = sendtime;
		this.setReceivers(userInfos);

	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Date sendtime) {
		this.sendtime = sendtime;
	}



	public UserInfo getSender() {
		return sender;
	}

	/**
	 * @param sender the sender to set
	 */
	public void setSender(UserInfo sender) {
		this.sender = sender;
	}

	/**
	 * @return the receivers
	 */
	public Set<UserInfo> getReceivers() {
		return receivers;
	}

	/**
	 * @param receivers the receivers to set
	 */
	public void setReceivers(Set<UserInfo> receivers) {
		this.receivers = receivers;
	}

}
