package com.latewind.domain;
// Generated 2016-5-5 21:53:57 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Position generated by hbm2java
 */
public class Position implements java.io.Serializable {

	private Integer positionId;
	private Department department;
	private Position superior;
	private String name;
	private String func;
	private Set<Position> positions = new HashSet<Position>(0);
	private Department leaderDepart;
	
	
	public Position() {
	}
	
	
	/**
	 * @param positionId
	 * @param department
	 * @param superior
	 * @param name
	 * @param func
	 * @param positions
	 * @param chiefDepart
	 * @param employees
	 */
	public Position(Integer positionId, Department department, Position superior, String name, String func,
			Set<Position> positions, Department leaderDepart, Set<Employee> employees) {
		super();
		this.positionId = positionId;
		this.department = department;
		this.superior = superior;
		this.name = name;
		this.func = func;
		this.positions = positions;
		this.leaderDepart = leaderDepart;
		this.employees = employees;
	}


	public Integer getPositionId() {
		return positionId;
	}
	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}
	public Department getDepartment() {
		return department;
	}
	public void setDepartment(Department department) {
		this.department = department;
	}
	public Position getSuperior() {
		return superior;
	}
	public void setSuperior(Position superior) {
		this.superior = superior;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getFunc() {
		return func;
	}
	public void setFunc(String func) {
		this.func = func;
	}
	public Set<Position> getPositions() {
		return positions;
	}
	public void setPositions(Set<Position> positions) {
		this.positions = positions;
	}

	public Department getLeaderDepart() {
		return leaderDepart;
	}


	public void setLeaderDepart(Department leaderDepart) {
		this.leaderDepart = leaderDepart;
	}

	private Set<Employee> employees = new HashSet<Employee>(0);
	
	/**
	 * @return the employees
	 */
	public Set<Employee> getEmployees() {
		return employees;
	}
	/**
	 * @param employees the employees to set
	 */
	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}


}
