package com.latewind.domain;
// Generated 2016-5-31 18:59:52 by Hibernate Tools 4.3.1.Final

/**
 * Processes generated by hbm2java
 */
public class Processes implements java.io.Serializable {

	private int id;
	private Integer materialsId;
	private String processesText;
	private Integer userinfoId;
	private String mytext;

	public Processes() {
	}

	public Processes(int id) {
		this.id = id;
	}

	public Processes(int id, Integer materialsId, String processesText, Integer userinfoId, String mytext) {
		this.id = id;
		this.materialsId = materialsId;
		this.processesText = processesText;
		this.userinfoId = userinfoId;
		this.mytext = mytext;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getMaterialsId() {
		return this.materialsId;
	}

	public void setMaterialsId(Integer materialsId) {
		this.materialsId = materialsId;
	}

	public String getProcessesText() {
		return this.processesText;
	}

	public void setProcessesText(String processesText) {
		this.processesText = processesText;
	}

	public Integer getUserinfoId() {
		return this.userinfoId;
	}

	public void setUserinfoId(Integer userinfoId) {
		this.userinfoId = userinfoId;
	}

	public String getMytext() {
		return this.mytext;
	}

	public void setMytext(String mytext) {
		this.mytext = mytext;
	}

}
