package com.latewind.test;
// Generated 2016-3-19 21:34:12 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import com.latewind.test.Userinfo;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private Integer id;
	private Userinfo userinfo;
	private String orderno;
	private int no;
	private String customer;
	private String figureno;
	private String mould;
	private String model;
	private int length;
	private int plancount;
	private double weight;
	private String alloystate;
	private Date deliverydate;
	private Date orderdate;
	private String remarks;
	private byte[] figure;

	public Orders() {
	}

	public Orders(Userinfo userinfo, String orderno, int no, String customer, String figureno, String model, int length,
			int plancount, double weight, String alloystate, Date deliverydate, Date orderdate) {
		this.userinfo = userinfo;
		this.orderno = orderno;
		this.no = no;
		this.customer = customer;
		this.figureno = figureno;
		this.model = model;
		this.length = length;
		this.plancount = plancount;
		this.weight = weight;
		this.alloystate = alloystate;
		this.deliverydate = deliverydate;
		this.orderdate = orderdate;

	}

	public Orders(Userinfo userinfo, String orderno, int no, String customer, String figureno, String mould,
			String model, int length, int plancount, double weight, String alloystate, Date deliverydate,
			Date orderdate, String remarks, byte[] figure) {
		this.userinfo = userinfo;
		this.orderno = orderno;
		this.no = no;
		this.customer = customer;
		this.figureno = figureno;
		this.mould = mould;
		this.model = model;
		this.length = length;
		this.plancount = plancount;
		this.weight = weight;
		this.alloystate = alloystate;
		this.deliverydate = deliverydate;
		this.orderdate = orderdate;
		this.remarks = remarks;
		this.figure = figure;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Userinfo getUserinfo() {
		return this.userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public String getOrderno() {
		return this.orderno;
	}

	public void setOrderno(String orderno) {
		this.orderno = orderno;
	}

	public int getNo() {
		return this.no;
	}

	public void setNo(int no) {
		this.no = no;
	}

	public String getCustomer() {
		return this.customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	public String getFigureno() {
		return this.figureno;
	}

	public void setFigureno(String figureno) {
		this.figureno = figureno;
	}

	public String getMould() {
		return this.mould;
	}

	public void setMould(String mould) {
		this.mould = mould;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public int getLength() {
		return this.length;
	}

	public void setLength(int length) {
		this.length = length;
	}

	public int getPlancount() {
		return this.plancount;
	}

	public void setPlancount(int plancount) {
		this.plancount = plancount;
	}

	public double getWeight() {
		return this.weight;
	}

	public void setWeight(double weight) {
		this.weight = weight;
	}

	public String getAlloystate() {
		return this.alloystate;
	}

	public void setAlloystate(String alloystate) {
		this.alloystate = alloystate;
	}

	public Date getDeliverydate() {
		return this.deliverydate;
	}

	public void setDeliverydate(Date deliverydate) {
		this.deliverydate = deliverydate;
	}

	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public byte[] getFigure() {
		return this.figure;
	}

	public void setFigure(byte[] figure) {
		this.figure = figure;
	}

}
