package com.latewind.test;
// Generated 2016-3-19 21:34:12 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String chnname;
	private String profession;
	private String limit;
	private Set orderses = new HashSet(0);

	public Userinfo() {
	}

	public Userinfo(String username, String password, String chnname, String profession, String limit) {
		this.username = username;
		this.password = password;
		this.chnname = chnname;
		this.profession = profession;
		this.limit = limit;
	}

	public Userinfo(String username, String password, String chnname, String profession, String limit, Set orderses) {
		this.username = username;
		this.password = password;
		this.chnname = chnname;
		this.profession = profession;
		this.limit = limit;
		this.orderses = orderses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getChnname() {
		return this.chnname;
	}

	public void setChnname(String chnname) {
		this.chnname = chnname;
	}

	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	public String getLimit() {
		return this.limit;
	}

	public void setLimit(String limit) {
		this.limit = limit;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
